# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 18:51
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('answer', models.BooleanField(verbose_name='Is this the correct answer?')),
                ('rank', models.IntegerField(help_text='Display order?')),
                ('type', models.CharField(choices=[('radio', 'One selection allowed'), ('checkbox', 'Multiple selections allowed')], default='radio', help_text='Allow multiple checks or only one (checbox or radio)?', max_length=48)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursetitle', models.CharField(max_length=1024)),
                ('siteurl', models.URLField()),
                ('coursedesc', models.CharField(blank=True, max_length=4096)),
                ('siteinfo', models.CharField(blank=True, max_length=4096)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('completed', models.DateField(blank=True, null=True)),
                ('accesscode', models.CharField(blank=True, help_text='SEND THIS TO REVIEWERS TO GIVE THEM ACCESS:<br>https://llc.manoa.hawaii.edu/analytics/review/register/ACCESS_CODE_HERE', max_length=255, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Access Code')),
                ('instructors', models.ManyToManyField(related_name='_review_instructors_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=4096)),
                ('postdate', models.TimeField(blank=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Review')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('rank', models.IntegerField()),
                ('guide', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.BooleanField(verbose_name='Is this the correct answer?')),
                ('rank', models.IntegerField(choices=[(1, 'NEEDS ATTENTION'), (2, 'MEETS REQUIREMENTS'), (3, 'EXEMPLARY')], help_text='Scale. This also effects the order this option will appear.')),
                ('type', models.CharField(choices=[('radio', 'One selection allowed'), ('checkbox', 'Multiple selections allowed')], default='radio', help_text='Allow multiple checks or only one (checkbox or radio)?', max_length=48)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.ReviewQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewReportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitdate', models.DateTimeField(blank=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Review')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.IntegerField(choices=[(1, 'NEEDS ATTENTION'), (2, 'MEETS REQUIREMENTS'), (3, 'EXEMPLARY')])),
                ('lastactivity', models.TimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.ReviewQuestion')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Category name')),
                ('text', models.TextField(help_text='This is displayed above the list of questions you add to this category', verbose_name='Introduction text')),
                ('rank', models.IntegerField(help_text='This is used for determining the order of the categories', verbose_name='Category number')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=4096)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Question')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='NOT SET', max_length=512)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reviewsection',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.ReviewSurvey'),
        ),
        migrations.AddField(
            model_name='reviewquestion',
            name='section',
            field=models.ForeignKey(help_text='The section that this question is part of. The user sees each category in-order on a single page, with all questions belonging to the category on the page', on_delete=django.db.models.deletion.CASCADE, to='review.ReviewSection'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.ReviewSection'),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='presurv',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='review.Survey'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewers',
            field=models.ManyToManyField(related_name='_review_reviewers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.ReviewSurvey'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Survey'),
        ),
    ]
